# Copyright 2014 Dietrich Epp.
# This file is part of SGLib.  SGLib is licensed under the terms of the
# 2-clause BSD license.  For more information, see LICENSE.txt.

# Default configurations for new Cocoa projects, as of Xcode 6.0.1.

BASE_CONFIG = {
    'ALWAYS_SEARCH_USER_PATHS': 'NO',
    'CLANG_CXX_LANGUAGE_STANDARD': 'gnu++0x',
    'CLANG_CXX_LIBRARY': 'libc++',
    'CLANG_ENABLE_MODULES': 'YES',
    'CLANG_ENABLE_OBJC_ARC': 'YES',
    'CLANG_WARN_BOOL_CONVERSION': 'YES',
    'CLANG_WARN_CONSTANT_CONVERSION': 'YES',
    'CLANG_WARN_DIRECT_OBJC_ISA_USAGE': 'YES_ERROR',
    'CLANG_WARN_EMPTY_BODY': 'YES',
    'CLANG_WARN_ENUM_CONVERSION': 'YES',
    'CLANG_WARN_INT_CONVERSION': 'YES',
    'CLANG_WARN_OBJC_ROOT_CLASS': 'YES_ERROR',
    'CLANG_WARN_UNREACHABLE_CODE': 'YES',
    'CLANG_WARN__DUPLICATE_METHOD_MATCH': 'YES',
    'CODE_SIGN_IDENTITY': "-",
    'ENABLE_STRICT_OBJC_MSGSEND': 'YES',
    'GCC_C_LANGUAGE_STANDARD': 'gnu99',
    'GCC_WARN_64_TO_32_BIT_CONVERSION': 'YES',
    'GCC_WARN_ABOUT_RETURN_TYPE': 'YES_ERROR',
    'GCC_WARN_UNDECLARED_SELECTOR': 'YES',
    'GCC_WARN_UNINITIALIZED_AUTOS': 'YES_AGGRESSIVE',
    'GCC_WARN_UNUSED_FUNCTION': 'YES',
    'GCC_WARN_UNUSED_VARIABLE': 'YES',
    'MACOSX_DEPLOYMENT_TARGET': '10.10',
    'SDKROOT': 'macosx',
}

DEBUG_CONFIG = {
    'COPY_PHASE_STRIP': 'NO',
    'GCC_DYNAMIC_NO_PIC': 'NO',
    'GCC_OPTIMIZATION_LEVEL': '0',
    'GCC_PREPROCESSOR_DEFINITIONS': [
        "DEBUG=1",
        "$(inherited)",
    ],
    'GCC_SYMBOLS_PRIVATE_EXTERN': 'NO',
    'MTL_ENABLE_DEBUG_INFO': 'YES',
    'ONLY_ACTIVE_ARCH': 'YES',
}

RELEASE_CONFIG = {
    'COPY_PHASE_STRIP': 'YES',
    'DEBUG_INFORMATION_FORMAT': 'dwarf-with-dsym',
    'ENABLE_NS_ASSERTIONS': 'NO',
    'MTL_ENABLE_DEBUG_INFO': 'NO',
}
