#!/usr/bin/env python
# Copyright 2011-2012 Dietrich Epp.
# This file is part of SGLib.  SGLib is licensed under the terms of the
# 2-clause BSD license.  For more information, see LICENSE.txt.
import re, sys, os
OUT = 'mac2.txt'
TMP = OUT + '.tmp'
f = open(TMP, 'w')
try:
    text = open('/System/Library/Frameworks/Carbon.framework/'
                'Frameworks/HIToolbox.framework/Headers/Events.h', 'r').read()
    print >>f, '; Automatically generated by "mac.py"'
    for m in re.finditer(r'kVK_(\w+)\s*=\s*(\w+)', text):
        print >>f, '%d\t%s' % (int(m.group(2), 0), m.group(1))
    f.close()
    os.rename(TMP, OUT)
except:
    try:
        os.unlink(TMP)
    except OSError:
        pass
    raise
