/* This file is automatically generated by keycode.py.  */
#include "keyid.h"
#include <string.h>

static const char KEYID_NAME[526] =
"0\0001\0002\0003\0004\0005\0006\0007\0008\0009\0A\0B\0Backslash\0C\0CapsLoc"
"k\0Comma\0D\0Delete\0DeleteForward\0Down\0E\0End\0Enter\0Equals\0Escape\0F"
"\0F1\0F10\0F11\0F12\0F13\0F14\0F15\0F16\0F17\0F18\0F19\0F2\0F20\0F3\0F4\0F5"
"\0F6\0F7\0F8\0F9\0G\0Grave\0H\0Help\0Home\0I\0J\0K\0KP0\0KP1\0KP2\0KP3\0KP4"
"\0KP5\0KP6\0KP7\0KP8\0KP9\0KPAdd\0KPDivide\0KPEnter\0KPEquals\0KPMultiply\0"
"KPNumLock\0KPPoint\0KPSubtract\0L\0Left\0LeftAlt\0LeftBracket\0LeftControl"
"\0LeftGUI\0LeftShift\0M\0Minus\0N\0O\0P\0PageDown\0PageUp\0Period\0Q\0Quote"
"\0R\0Right\0RightAlt\0RightBracket\0RightControl\0RightGUI\0RightShift\0S\0"
"Semicolon\0Slash\0Space\0T\0Tab\0U\0Up\0V\0W\0X\0Y\0Z";

static const unsigned short KEYID_OFF[256] = {
 -1, -1, -1, -1, 20, 22, 34, 51, 79,105,178,186,198,200,202,316,
373,381,383,385,410,418,481,505,511,516,518,520,522,524,  2,  4,
  6,  8, 10, 12, 14, 16, 18,  0, 85, 98, 53,507,499,375, 91,331,
435, 24, -1,483,412,180, 45,403,493, 36,107,150,157,160,163,166,
169,172,175,110,114,118, -1, -1, -1, -1,193,396, 60, 81,387,420,
318, 74,513,287,250,276,305,244,259,208,212,216,220,224,228,232,
236,240,204,297, -1, -1, -1,267,122,126,130,134,138,142,146,153,
 -1, -1, -1, -1, -1,188, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
343,363,323,355,448,470,426,461, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
};

static const unsigned char KEYID_ORDER[109] = {
 39, 30, 31, 32, 33, 34, 35, 36, 37, 38,  4,  5, 49,  6, 57, 54,
  7, 42, 76, 81,  8, 77, 40, 46, 41,  9, 58, 67, 68, 69,104,105,
106,107,108,109,110, 59,111, 60, 61, 62, 63, 64, 65, 66, 10, 53,
 11,117, 74, 12, 13, 14, 98, 89, 90, 91, 92, 93, 94, 95, 96, 97,
 87, 84, 88,103, 85, 83, 99, 86, 15, 80,226, 47,224,227,225, 16,
 45, 17, 18, 19, 78, 75, 55, 20, 52, 21, 79,230, 48,228,231,229,
 22, 51, 56, 44, 23, 43, 24, 82, 25, 26, 27, 28, 29
};

int keyid_code_from_name(const char *name)
{
    unsigned l = 0, r = 109, m;
    int x, c;
    while (l < r) {
        m = (l + r) / 2;
        x = KEYID_ORDER[m];
        c = strcmp(name, KEYID_NAME + KEYID_OFF[x]);
        if (c < 0)
            r = m;
        else if (c > 0)
            l = m + 1;
        else
            return x;
    }
    return -1;
}

const char *keyid_name_from_code(int code)
{
    int off;
    if (code < 0 || code > 255)
        return 0;
    off = KEYID_OFF[code];
    if (off == (unsigned short) -1)
        return 0;
    return KEYID_NAME + off;
}
